### ISSUE TITLE
微信H5点击img会进入图片预览

### ISSUE THREAD

**Issue by hetianhe** [hetianhe/vue-tpl#40]
这是一个手机兼容性问题

### 方案一
```css
img {
  pointer-events: none;
}
```

### 方案二
```javascript
onClickDocument(event) {
  const target = event.target;
  // 监听点击的是图片时，禁止查看大图
    if (target.nodeName === 'IMG') {
      event.preventDefault();
    }
}
```
