### ISSUE TITLE
避免浏览器自动填充表单的解决方式

### ISSUE THREAD

**Issue by hetianhe** [hetianhe/vue-tpl#47]
1. 一定要给type='text'一个id;
2. type='password'不能有id或者name（有其一都会导致自动填充），可以有class;
3.目测这种方式在360上行不通，谷歌没有问题，谨慎；
4. 去掉那个黄色的背景
```css
input:-webkit-autofill {
  -webkit-box-shadow: 0 0 0 1000px white inset !important;
}
input:-webkit-autofill {
  transition: background-color 5000s ease-in-out 0s;
}
```
