### ISSUE TITLE
pointer-events初识

### ISSUE THREAD

**Issue by hetianhe** [hetianhe/vue-tpl#60]
微信h5，小部分android机型，点击img标签会图片预览模式，
可以通过css来禁止
```css
img {
  pointer-events: none;
}
```
同时，也会禁止识别二维码的功能，所以需要用类区分
```css
img.code {
  pointer-events: auto;
}
```
此外，还有其它的用法，参考[张鑫旭大大的文章](https://www.zhangxinxu.com/wordpress/2011/12/css3-pointer-events-none-javascript/)
